### ISSUE TITLE
Сомнительно, почти окэй

### ISSUE THREAD

**Issue by HukuTa45** [Naabway1/EmployeeManagement#1]
https://github.com/Naabway1/EmployeeManagement/blob/c2e6dbc55d4f7e9ff88b6ce78b20cd0c64468963/EmployeeManagement/View/EditPage.xaml.cs#L22

Ну я подразумевал что будет переключение фреймов и логика написанная в в классах этих страниц...

Как я тебя понимаю, но у меня есть еще вы :)
![image](https://github.com/user-attachments/assets/e2994474-d515-4ae6-a95d-080880b40dc8)

**Comment by HukuTa45** [comment]
"Добавить" не работает :(

**Comment by HukuTa45** [comment]
Но ты единственный кто сделал через .Source

**Comment by Naabway1** [comment]
Извините, мне стыдно...
А насчёт написания в код бихайнде... Там было написано что можно использовать мввм, ну я его и использовал, но я не понимаю в чем проблема с кнопками и релей командом, они у меня просто не работают, точнее, работают некорректно и я не понимаю что именно не так ;(

**Comment by HukuTa45** [comment]
+такие сокращения ненада
![image](https://github.com/user-attachments/assets/899e22aa-9791-46e4-a073-e0dedebb3d03)

**Comment by HukuTa45** [comment]
Вот пример как можно было бы сделать https://github.com/HukuTa45/EmployeeApplication
Вместо new Page можно было заюзать Uri, по большей части все отличия

А вы пошли по тёмной тропинке

**Comment by HukuTa45** [comment]
Идея была в том чтоб показать как меняются фреймы и экраны в рамках одного окна

**Comment by HukuTa45** [comment]
> но я не понимаю в чем проблема с кнопками и релей командом, они у меня просто не работают, точнее, работают некорректно и я не понимаю что именно не так ;(

Разделить по разным классам, у тебя же есть страницы, вот на них кнопки и делать, привязывать логику на кнопки, которые открываются на этой фрейме

**Comment by Naabway1** [comment]
Так как будто-бы нарушение мввм, разве нет? мввм же предполагает отсутствие кода в код бихайнде, ну или минимальное его наличие в виде привязки дата контекста... Да и тем более, у меня в прошлой работе хотя бы кнопка добавления работала, тот же подход, абсолютно, только в этой работе она не работает xDDDD
